# Project with quota & limits
---
apiVersion: project.fydrah.com/v1alpha1
kind: Project
metadata:
  name: sample1
spec:
  limitRange:
    limits:
      - default:
          cpu: 100m
          memory: 256Mi
        defaultRequest:
          cpu: 10m
          memory: 128Mi
        type: Container

  resourceQuota:
    hard:
      requests.cpu: 1
      requests.memory: 1Gi
      limits.cpu: 2
      limits.memory: 2Gi

# Project with limits only
---
apiVersion: project.fydrah.com/v1alpha1
kind: Project
metadata:
  name: sample2
spec:
  limitRange:
    limits:
      - default:
          cpu: 100m
          memory: 256Mi
        defaultRequest:
          cpu: 10m
          memory: 128Mi
        type: Container

# Project with quota only
---
apiVersion: project.fydrah.com/v1alpha1
kind: Project
metadata:
  name: sample3
spec:
  resourceQuota:
    hard:
      requests.cpu: 1
      requests.memory: 1Gi
      limits.cpu: 2
      limits.memory: 2Gi


# Project without quota or limits
---
apiVersion: project.fydrah.com/v1alpha1
kind: Project
metadata:
  name: sample4
